### ISSUE TITLE
Month Picker UX suggestions

### ISSUE THREAD

**Issue by MB-Motive** [drivardxrm/FluentUI.MonthPicker.PCF#1]
Hi David

Great PCF, exactly what I was looking for and looks great. Thanks for creating this!

Just a couple of UX improvements I thought could improve it: 

- Currently the month picker dialog is only opened when the user clicks on the calendar icon. From a UX perspective is it possible to also have the dialog open when clicking on the displayed month/year (or anywhere in the field)?

- When a user selects a month the value is set on the component, but the dialog doesn't react. Can the dialog close when a month is selected?

- When the field that the component is attached to is set to null using Javascript, the component continues to display the last selected month/year. Can the component be cleared when the value is set to null?

Thanks again for creating this. 
Matt

**Comment by drivardxrm** [comment]
Hi @MB-Motive,

I will see what I can do.

Thanks for your feedback, It's really appreciated.

**Comment by drivardxrm** [comment]
Hi @MB-Motive ,

Have a look at then latest release, I implemented your suggestions.
https://github.com/drivardxrm/FluentUI.MonthPicker.PCF/releases/tag/v1.0.0.1

**Comment by MB-Motive** [comment]
Thanks for the update @drivardxrm. The new release works great! Really appreciate the quick response and update.

I notice that the control still displays the selected month/year after JavaScript sets it back to null, however this wasn't as important as the other two UX suggestions.

**Comment by drivardxrm** [comment]
@MB-Motive ,
I finally got time to work on the control issues.
latest release (v1.0.0.3) fixes your latest comment.
